#!/usr/bin/env bash
# Interactive Q&A installer for the worktree-pane skill.
# Run from a terminal:  bash ~/.claude/skills/worktree-pane/install.sh
# It detects your environment, asks a few questions (all with sensible
# defaults — just press Enter), writes a config file, and optionally adds a
# `wt` shell alias so you can use it outside Claude too.
set -eu

SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$SKILL_DIR/scripts/worktree-pane.sh"
CONFIG_DIR="$HOME/.config/worktree-pane"
CONFIG_FILE="$CONFIG_DIR/config.env"

ask() {  # ask "Question" "default" -> echoes answer (default if empty)
  local q="$1" def="${2:-}" ans=""
  if [ -n "$def" ]; then printf '%s [%s]: ' "$q" "$def" >&2
  else printf '%s: ' "$q" >&2; fi
  read -r ans || true
  [ -n "$ans" ] && printf '%s' "$ans" || printf '%s' "$def"
}

echo "=== worktree-pane installer ==="
echo

# --- detect environment ---
detected_mux="none"
if [ -n "${TMUX:-}" ]; then detected_mux="tmux"
elif command -v cmux >/dev/null 2>&1; then detected_mux="cmux"; fi

detected_base=""
if git rev-parse --show-toplevel >/dev/null 2>&1; then
  detected_base=$(git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's@^origin/@@' || true)
fi

echo "Detected multiplexer : $detected_mux"
echo "Detected default base: ${detected_base:-<none / not in a repo>}"
echo

# --- Q&A ---
mux=$(ask "Multiplexer to use (auto/tmux/cmux/none)" "auto")
wt_root=$(ask "Worktree directory (repo-relative or absolute)" ".claude/worktrees")
echo
echo "Branch naming: ticket names like FOO-123 become <prefix>FOO-123."
prefix=$(ask "Branch prefix (blank for none)" "feature/")
base_override=$(ask "Default base branch (blank = auto-detect each time)" "")
echo
echo "Pane agent: what runs in the new pane — 'auto' launches the agent that"
echo "opened it (Claude/Kiro/Codex...), 'none' opens a shell, or a custom command."
agent=$(ask "Pane agent (auto/none/command)" "auto")

# --- write config ---
mkdir -p "$CONFIG_DIR"
{
  echo "# worktree-pane config — generated by install.sh"
  echo "WORKTREE_PANE_MUX=$mux"
  echo "WORKTREE_PANE_ROOT=$wt_root"
  echo "WORKTREE_PANE_BRANCH_PREFIX=$prefix"
  echo "WORKTREE_PANE_BASE=$base_override"
  echo "WORKTREE_PANE_AGENT=$agent"
} > "$CONFIG_FILE"
chmod +x "$SCRIPT" 2>/dev/null || true
echo
echo "✓ wrote $CONFIG_FILE"

# --- optional shell alias ---
echo
add_alias=$(ask "Add a 'wt' shell alias so you can run it from any terminal? (y/N)" "N")
case "$add_alias" in
  y|Y|yes|YES)
    rc=""
    case "${SHELL:-}" in
      *zsh)  rc="$HOME/.zshrc" ;;
      *bash) rc="$HOME/.bashrc" ;;
      *) rc=$(ask "Shell rc file to edit" "$HOME/.zshrc") ;;
    esac
    line="alias wt='bash $SCRIPT'"
    if [ -f "$rc" ] && grep -qF "$line" "$rc"; then
      echo "  alias already present in $rc"
    else
      printf '\n# worktree-pane\n%s\n' "$line" >> "$rc"
      echo "  ✓ added 'wt' alias to $rc (open a new shell or: source $rc)"
    fi
    ;;
  *) echo "  skipped alias." ;;
esac

echo
echo "Done. Try it:"
echo "  bash $SCRIPT <TICKET-OR-NAME>"
echo "Or, inside Claude Code, just say: \"<TICKET> 워크트리 만들어줘\""
